services:
  servicesite-db:
    image: postgres:16-alpine
    env_file:
      - .env.docker
    networks:
      default:
        aliases:
          - 
          - db
    healthcheck:+
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - servicesite-db-data:/var/lib/postgresql/data

  servicesite-backend:
    image: ghcr.io/countryboy0ner/dubcast-api:sha-8e79b4d
    env_file:
      - .env.docker
    depends_on:
      servicesite-db:
        condition: service_healthy
    ports:
      - "8089:8080"
    restart: unless-stopped

volumes:
  servicesite-db-data:
